export const ADD_ALL_USERS = "ADD_ALL_USERS";
export const ADD_ALL_TODOS = "ADD_ALL_TODOS";
export const MODIFY_TODO_CHECKBOX = "MODIFY_TODO_CHECKBOX";
export const ADD_ALL_POSTS = "ADD_ALL_POSTS/POST_REDUCER";
export const ADD_POST = "ADD_POST/POST_REDUCER";
